service: default
runtime: custom # go112 for standard env
# need flex environment for websockets to work
env: flex # use standard otherwise

# manual scaling to prevent overages
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
