name: Upload Docs
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: cd docs && yarn && yarn build && cd -
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
      - name: finish
        run: echo "finished!"
