name: Upload Frontend
on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/actions/build-frontend/**"
      - ".github/workflows/frontend.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checks out a copy of the repo
      - uses: actions/checkout@master
      - uses: ./.github/actions/build-frontend
        env:
          AWS_S3_BUCKET: mailpear-frontend
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          BUILD: "true"
